### ISSUE TITLE
Pre-trained model on AMI dataset

### ISSUE THREAD

**Issue by kam1107** [pyannote/pyannote-audio#101]
Hi, 
I would like to try the diarization pipeline on my own dataset, and was wondering if there is any pre-trained model that you can release (e.g. ${TRAIN_DIR}/weights/0050.pt)?

Thank you very much.
Kam

**Comment by hbredin** [comment]
No. Sorry. At least, not in the short term.

**Comment by ChristopherLu** [comment]
@hbredin 

For curiosity, have you ever tried fine-tuning a speaker identification/authentication model on a new dataset (e.g., AMI), given a  pre-trained model on another audio dataset (e.g., Voxceleb)? The fine-tuning here refers to network tuning instead of PDLA adaption in literature (e.g., xvector). 

My question is that with many neural speaker ID systems recently proposed and large audio corpus released, is there any way to make the training of these systems more efficient on in-domain dataset (i.e., knowledge transfer)? Training from scratch whenever a domain change happens is far from ideal.

**Comment by hbredin** [comment]
> @hbredin
> 
> For curiosity, have you ever tried fine-tuning a speaker identification/authentication model on a new dataset (e.g., AMI), given a pre-trained model on another audio dataset (e.g., Voxceleb)? The fine-tuning here refers to network tuning instead of PDLA adaption in literature (e.g., xvector).

I have been willing to try this for a while but haven’t had the chance to do that yet.

> My question is that with many neural speaker ID systems recently proposed and large audio corpus released, is there any way to make the training of these systems more efficient on in-domain dataset (i.e., knowledge transfer)? Training from scratch whenever a domain change happens is far from ideal.

I agree we should look at this problem. 

The NLP community is doing it (https://thegradient.pub/nlp-imagenet) — we should too :)
