### ISSUE TITLE
long format audio

### ISSUE THREAD

**Issue by jgframoz** [pyannote/pyannote-audio#1090]
Hi!

I tried a couple of examples on Google Colab, but every time I try some sort of long-format audio, it takes too long to process `pipeline()`. 

I'm currently testing with 15min audio files and letting it run for more than 1 hour and it doesn't finish.

My question is, have you tried 'big' audio files? Like between 15min and 2 hours? If yes, how long did it take?

**Comment by hbredin** [comment]
Yes. Some of the benchmarks reported [here](https://huggingface.co/pyannote/speaker-diarization#accuracy) contains long (one hour) audio.

If you happen to know a rough estimation of the number of speakers, you might make things slightly faster by providing an upper bound to the number of speakers:

```python
pipeline("audio.wav", max_speakers=...)
```

**Comment by ccostes** [comment]
Looking into this I tried timing the execution for varying audio input lengths (running locally on a GPU) and found it was relatively fast up to 10-minutes (max 30-40 seconds), but never returned when trying it with a 14-minute input, so it seems like something is getting stuck rather than just taking a long time to run.

Any advice on trying to narrow down where it might be getting stuck?
