### ISSUE TITLE
ImportError: cannot import name 'VersionInfo' from 'semver'

### ISSUE THREAD

**Issue by ainnotate** [pyannote/pyannote-audio#1101]
Hi, 

Thanks for this awesome project. 
I'm trying to test pyannotate-audio on my Ubuntu 20.04 and I'm following the instructions from the home page using conda (shown below)

```
conda create -n pyannote python=3.8
conda activate pyannote

# pytorch 1.11 is required for speechbrain compatibility
# (see https://pytorch.org/get-started/previous-versions/#v1110)
conda install pytorch==1.11.0 torchvision==0.12.0 torchaudio==0.11.0 -c pytorch

pip install pyannote.audio

```
Post installation, I'm using the below code for testing,

```
# instantiate pretrained speaker diarization pipeline
from pyannote.audio import Pipeline
pipeline = Pipeline.from_pretrained("pyannote/speaker-diarization")

# apply pretrained pipeline
diarization = pipeline("audio.wav")

# print the result
for turn, _, speaker in diarization.itertracks(yield_label=True):
    print(f"start={turn.start:.1f}s stop={turn.end:.1f}s speaker_{speaker}")
# start=0.2s stop=1.5s speaker_A
# start=1.8s stop=3.9s speaker_B
# start=4.2s stop=5.7s speaker_A
# ...
```
I get the below error,

`ImportError: cannot import name 'VersionInfo' from 'semver'`

I tried uninstalling semver and tried installing through conda, nothing helped. Any thoughts on this issue?

Thank you.

**Comment by hbredin** [comment]
To maximise the probability of someone answering your question:

* if your issue is a bug report, please provide a [minimum reproducible example](https://stackoverflow.com/help/minimal-reproducible-example), e.g. a link to a self-contained [Google Colab](https://colab.research.google.com/) notebook (i.e. containing everthing needed to reproduce the bug: installation of pyannote.audio, downloads of models or test data, etc...)

* if your issue is a feature request, please [read this](https://xyproblem.info/) first and update your request accordingly.

**Comment by ainnotate** [comment]
for some reason semver on my env was behaving weiredly. I had to manually remove and installed semver again. It worked again. Thanks for your support.
