### ISSUE TITLE
An error was encountered while loading "pyannote/speaker-diarization" 

### ISSUE THREAD

**Issue by Zpadger** [pyannote/pyannote-audio#1128]
Hello，when i run the code :
```
from pyannote.audio import Pipeline
pipeline = Pipeline.from_pretrained("pyannote/speaker-diarization",
                                    use_auth_token="my_token")
```
I get an error :
```
Traceback (most recent call last):
  File "/home/dg/anaconda3/envs/pyannote/lib/python3.8/site-packages/huggingface_hub/utils/_errors.py", line 213, in hf_raise_for_status
    response.raise_for_status()
  File "/home/dg/anaconda3/envs/pyannote/lib/python3.8/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://huggingface.co/pyannote/segmentation/resolve/2022.07/pytorch_model.bin
```
whether I use the **read token role** or the **write token role**.
Anyone else know how to fix it? Thx.

**Comment by micahjon** [comment]
Thanks for posting! I'm running into a similar error when using a read token:

```python
pipeline = Pipeline.from_pretrained("pyannote/speaker-diarization",
                                            use_auth_token="hf_E...rest of token here")
```

```
401 Client Error: Repository Not Found for url: https://huggingface.co/pyannote/segmentation/resolve/2022.07/pytorch_model.bin. 
If the repo is private, make sure you are authenticated
```

I'm able to access the [segmentation repository](https://huggingface.co/pyannote/segmentation) just fine in my browser and agreed to the license, but for some reason the token isn't working.

**Comment by pooya-mohammadi** [comment]
the same error here

**Comment by mezaros** [comment]
Same error here, whatever is going on with the tokens is broken and the project has been unusable since 10/27.

**Comment by pooya-mohammadi** [comment]
It seems the models have become private. Answering two or three simple questions allows access to the models. However, I couldn't download them using the `use_auth_toekn` variable.

**Comment by pooya-mohammadi** [comment]
@micahjon 
@Zpadger 
`use_auth_token` works fine. You simply need to update your pyannote.audio because in the new version [get_model](https://github.com/pyannote/pyannote-audio/blob/develop/pyannote/audio/pipelines/utils/getter.py#L35) takes `use_auth-token` as an input and it works fine. This is added in the new release, so a simple update to latest version would solve the problem!

**Comment by JoFrhwld** [comment]
It looks like you need to fill out the user agreement on *both* hf.co/pyannote/speaker-diarization and hf.co/pyannote/segmentation

**Comment by raulqf** [comment]
It seems to be working. I've installed a new environment and reproduced the diarization example.

**Comment by subtyping** [comment]
Installed new environment and was able to get things working. I was still encountering the error after accepting both agreements listed by @JoFrhwld - so not sure if agreeing to both of those is needed or not. Either way, fresh install works!

**Comment by MrEdwards007** [comment]
It works now.

I had uninstalled and reinstalled a few times but that did **not** by itself resolve the issue.
When this was previously working a few days ago before the update, I had already accepted the diarization agreement.
What **did** resolve the issue was **_also_** accepting the segmentation agreement, as @JoFrhwld  suggested.

**Comment by mezaros** [comment]
I'm running the correct 2.1 version, I did go through both diarization and segmentation gateways even though it wasn't specified, I have updated my token a hundred times — and, with nothing changing in my environment, the error has migrated from 403 forbidden documented above to a new SemVer error. Sounds like I need to completely wipe my environment and start over, even though I was already on the correct versions.

Bugs I understand. But why this friction in the first place? It feels developer and user hostile.

**Comment by Frascth** [comment]
similiar problem
in my case, agreeing all neccessary model in hugging face, use the read token, huggingface-cli login using created token, and finnaly upgrade the pyannote.audio library to 2.1.1 using (pip install --upgrade pyannote.audio) solved my problem

**Comment by cetiny** [comment]
Agreeing to all the models on Huggingface resolved the issue for me (thanks @JoFrhwld ). Any tips how to save the model locally and access from cache? I don't want my code to be broken like this again.

**Comment by MrEdwards007** [comment]
Yes, I thought the model was downloaded and really want this to work offline.

**Comment by shashankmc** [comment]
Updating to the latest version of the library and generating ``use_auth_token`` for both ``speaker-diarization`` and ``segmentation`` seems to do the trick. Tested if using certain auth token would create an issue but it doesn't matter which ``access token`` is provided once both are generated.

**Comment by mezaros** [comment]
Got it working with a full environment reset.

But, no longer enthused about testing this. We could never, ever rely on it or ask anyone else to, after this experience. The models need to work offline.

**Comment by pranjal-zipteams** [comment]
> It works now.
> 
> I had uninstalled and reinstalled a few times but that did **not** by itself resolve the issue. When this was previously working a few days ago before the update, I had already accepted the diarization agreement. What **did** resolve the issue was **_also_** accepting the segmentation agreement, as @JoFrhwld suggested.

This fixes the issue for me.

**Comment by plandrobe** [comment]
> https://huggingface.co/pyannote/segmentation/resolve/2022.07/pytorch_model.bin.

Same here. I have already accepted the terms in both repos, download a new token, updated hugging face hub and pyannote.audio to the last versión. The api response is generic for when the url or model is not found (it doesn't matter if the problem is the token or not). Look at the url of the pretrained model in the error that ends with bin. (a dot at the end). If you try the url without the dot in the browser you can download the file fine. Looks like a bug, at some point the code is adding a . (dot) in the file request.

**Comment by makkasu** [comment]
Some variant on the issue here: I've signed up on the hub to the terms for both models, generated the auth token and I can use it locally on my laptop. However, when I try to run it in an Azure VM, it just hangs on `pipeline = Pipeline.from_pretrained('pyannote/speaker-diarization', use_auth_token=...` until the max HTTPS retries is exceeded. Quite frustrating, can't really proceed with development using this tool until this hurdle is removed.

**Comment by hbredin** [comment]
I have just updated the [FAQ](https://github.com/pyannote/pyannote-audio/blob/develop/FAQ.md#can-i-use-gated-models-and-pipelines-offline) with instructions on how to use pretrained models and pipelines offline.

**Comment by pri1712** [comment]
Upgrading my pyannote.audio version worked for me as well.

**Comment by Dheeru1801** [comment]
i am getting the error : ValueError: Revisions must be passed with `revision` keyword argument,,,,while creating the pipeline..somebody tell me what should i do
