### ISSUE TITLE
Running out of RAM when performing speaker segmentation

### ISSUE THREAD

**Issue by Laope94** [pyannote/pyannote-audio#1147]
Greetings,

I am using pipeline with speaker-segmentation@2.1 model. However, pipeline is failing with "Process finished with exit code 137" message when I am trying to process long audio file (approximately one and half hour long flac file, 86mb, 16khz sample rate) - it's running out of memory (machine with 32GB RAM, also GPU is present), then resorts to swapping and then keeps going towards slow death.

Is this somekind of memory leak within pipeline or is it just growing object with segments? There is no issue with small files, I have another file 13 minutes long and segmentation is done in few seconds, almost no effect to RAM. 
Is there any way around this? I am considering using somekind of primitive pre-segmentation based on longer periods of silence in file, like 1-2 seconds, and then feeding chunks to the models, but there is no guarantee there will always be such big silent periods so I'd like something more elegant.

**Comment by hbredin** [comment]
To maximise the probability of someone answering your question:

* if your issue is a bug report, please provide a [minimum reproducible example](https://stackoverflow.com/help/minimal-reproducible-example), e.g. a link to a self-contained [Google Colab](https://colab.research.google.com/) notebook (i.e. containing everthing needed to reproduce the bug: installation of pyannote.audio, downloads of models or test data, etc...)

* if your issue is a feature request, please [read this](https://xyproblem.info/) first and update your request accordingly.
