### ISSUE TITLE
Authentication Token Error

### ISSUE THREAD

**Issue by samecfrank** [pyannote/pyannote-audio#1191]
### Discussed in https://github.com/pyannote/pyannote-audio/discussions/1190

<div type='discussions-op-text'>

<sup>Originally posted by **samecfrank** December 12, 2022</sup>
I am using pyannote.audio for speaker diarization by running the code shown below. 
```
pipeline = pyannote.audio.Pipeline.from_pretrained("pyannote/speaker-diarization@2.1",use_auth_token = auth_token)
diarization = pipeline(file_name,num_speakers = num_speakers)
```
I followed the steps given on the hugging face website for making an authentication token (see below)
```
# 1. visit hf.co/pyannote/speaker-diarization and accept user conditions
# 2. visit hf.co/pyannote/segmentation and accept user conditions
# 3. visit hf.co/settings/tokens to create an access token
# 4. instantiate pretrained speaker diarization pipeline
```
However, I am still getting the following error. Does anyone know why this may be? Thank you! 

`RepositoryNotFoundError: 401 Client Error: Repository Not Found for url: https://huggingface.co/pyannote/segmentation/resolve/2022.07/pytorch_model.bin. If the repo is private, make sure you are authenticated. (Request ID: Root=1-639750ac-45de6da3313b2ee6787c69cb)`</div>

**Comment by hbredin** [comment]
This has been discussed several times in multiple issues.
Did you update to the latest version of `pyannote.audio`?

**Comment by NathanielParizi** [comment]
I can chime in, I'm experiencing the same issue.
I have updated to the latest version of pyannote.audio 

pip install --upgrade pyannote.audio.

I'll try to reproduce the issue with the steps that I took and post here. Thank you @hbredin

**Comment by NathanielParizi** [comment]
**Repro Steps:**


Create an account and sign in
Agree to the terms on https://huggingface.co/pyannote/speaker-diarization
		- Enter name of Company
		- Purpose of using the model
Agree to the terms on https://huggingface.co/pyannote/segmentation
		- Enter name of Company
		- Purpose of using the model

Verify account in email 
	Your email address has been verified successfully.

Create a new access token
		Name - Diarization
		READ access


from pyannote.audio import Pipeline, Model



model = Model.from_pretrained("pyannote/segmentation",
                              "VALID_TOKEN")




_Could not download 'pyannote/segmentation' model.
It might be because the model is private or gated so make
sure to authenticate. Visit https://hf.co/settings/tokens to
create your access token and retry with:

   >>> Model.from_pretrained('pyannote/segmentation',
   ...                       use_auth_token=YOUR_AUTH_TOKEN)

If this still does not work, it might be because the model is gated:
visit https://hf.co/pyannote/segmentation to accept the user conditions._
