### ISSUE TITLE
Preloading Known Speaker Embeddings for Speaker Identification and Improving Cluster accuracy

### ISSUE THREAD

**Issue by alexmoini** [pyannote/pyannote-audio#1224]
It would be really useful to be able to load existing embeddings for known speakers before intaking audio. This would serve as an improvement to the clustering accuracy and solve a speaker identification problem at the same time.

Heres an example: If I know "John" and "Sarah" are going to be 2 of the 3 speakers in the audio file that needs to be diarized and transcribed. Assuming I already have embeddings for John and Sarahs voice, it would be a great feature to be able to preload these embeddings into the clustering and instead of receiving output of "Speaker 1" or "Speaker 2" for John and Sarah respectively, it would be "John" and "Sarah". Thus improving the clustering accuracy and doing speaker identification at the same time.

**Comment by hbredin** [comment]
Related to #1205 #1218 #1085. 

Feel free to contribute a PR adding this feature -- I will gladly have a look at it.

**Comment by bghorvath** [comment]
Hi! I started working on a similar feature, but instead of being able to add the previously computed speaker embeddings to the clustering space, my approach is being able to initialize a pipeline with fitted cluster centroids. This would of course mean the algorithm couldn't learn more speakers.
My main issue with diarization (apart from speaker identification across multiple audio files) is computational resources: I don't want to refit the clusters each time if I already computed the centroids previously.
With your approach I'd be worried about the space and time complexity of the clustering algorithms: too many data points to fit the clusters on would make diarization very slow. Any idea how to solve this problem?

**Comment by bghorvath** [comment]
@alexmoini thank you for the suggestions! Today I experimented with your method on dummy data, to me it seemed like using a threshold for separating the data points doesn't really work, the distribution of the distances can vary too much. Instead I fit a Gaussian Mixture model to separate the points that have to be classified using the previous clusters, from the points that need new cluster(s). Do you see anything wrong with this approach? The results seem promising, but I'll have to test it on real life, messy, audio embedding data. If that will work, I'll finish my PR and submit it.
You can check out my experiment here if you're interested: https://github.com/bghorvath/aggClusterKNNExpansion/blob/main/cluster_expansion.ipynb
