### ISSUE TITLE
WinError 1314 with the Speaker-Diarization

### ISSUE THREAD

**Issue by Kalle-crypto** [pyannote/pyannote-audio#1232]
Hey frens,
when I'm using the described setup for pyannotes speaker-diarization:

from pyannote.audio import Pipeline
pipeline = Pipeline.from_pretrained("pyannote/speaker-diarization@2.1",
                                    use_auth_token="ACCESS_TOKEN_GOES_HERE")

and putting my hf-token in there it is still displaying "OSError: [WinError 1314] Dem Client fehlt ein erforderliches Recht:" which might be something like "The client is missing a required right:" in English. It seems to be occuring in user\\.cache\\huggingface\\hub\\models--speechbrain--spkrec-ecapa-voxceleb\\snapshots\\5c0be3875fda05e81f3c004ed8c7c06be308de1e\\hyperparams.yaml' -> user\\.cache\\torch\\pyannote\\speechbrain\\hyperparams.yaml'.

I also put the segmentation model in the code which was downloading. Only other issue displayed in the terminal might be "The torchaudio backend is switched to 'soundfile'. Note that 'sox_io' is not supported on Windows."

I'm neither an english native nor a skilled programmer so please don't be pissed if something similar has been asked before. Read and tried anything from the previous issues that seemed similar to me.
How do I solve this?
Thanks and have a nice Day :)

**Comment by theyaoster** [comment]
I had the exact same output on `hyperparams.yaml`. The English version of the message is:

```
OSError: [WinError 1314] A required privilege is not held by the client:
```

The issue is you need to be in a command prompt with elevated permissions. Try running your terminal as administrator and try again (for VSCode users, you'll need to run VSCode as admin).

Reference: https://stackoverflow.com/questions/37700536/visual-studio-code-terminal-how-to-run-a-command-with-administrator-rights
