### ISSUE TITLE
Issues with multi-gpus training

### ISSUE THREAD

**Issue by fabiocat93** [pyannote/pyannote-audio#1238]
Hi,

I want to train a voice segmenter. My script works well with one single GPU, but when I switch to multiple GPUs, it stacks before the first epoch. 

<img width="708" alt="Screenshot 2023-01-23 at 11 49 41" src="https://user-images.githubusercontent.com/15893011/214099397-7ec95af6-97a2-4d03-935b-b2769409862d.png">

Here is my code for launching the training (I took inspiration from the following tutorial: https://pytorch-lightning.readthedocs.io/en/latest/clouds/cluster_advanced.html).

```
trainer = pl.Trainer(accelerator='gpu',
                     devices=8,
                     num_nodes=4,
                     max_epochs=max_epochs,
                     limit_train_batches=1.0,
                     strategy=DDPStrategy(find_unused_parameters=False), 
                     callbacks=[model_checkpoint, early_stopping],
                     logger=logger,
                     )
```

And here is the slurm config file.
```
#!/bin/bash                      
#SBATCH --job-name=train
#SBATCH -t 10:00:00          
#SBATCH -n 4
#SBATCH --cpus-per-task=8 
#SBATCH --mem=400G
#SBATCH --gres=gpu:tesla-v100:8
#SBATCH --ntasks-per-node=8
# Execute commands to run your program here. Here is an example of python.
srun python my_train.py
```

1. Is multi-gpus training supported with the last version of pyannote-audio 2?
2. Is this issue connected with [#11910](https://github.com/Lightning-AI/lightning/issues/11910)?
3. Can you maybe suggest any solution?

**Comment by hbredin** [comment]
To maximise the probability of someone answering your question:

* if your issue is a bug report, please provide a [minimum reproducible example](https://stackoverflow.com/help/minimal-reproducible-example), e.g. a link to a self-contained [Google Colab](https://colab.research.google.com/) notebook (i.e. containing everthing needed to reproduce the bug: installation of pyannote.audio, downloads of models or test data, etc...)

* if your issue is a feature request, please [read this](https://xyproblem.info/) first and update your request accordingly.
