### ISSUE TITLE
Is there a way we can use custom clustering methods for speaker diarization task and get the annotation and rttm files ?

### ISSUE THREAD

**Issue by pranavtushar** [pyannote/pyannote-audio#1303]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
Add any other context about the feature request here.

**Comment by hbredin** [comment]
To maximise the probability of someone answering your question:

* if your issue is a bug report, please provide a [minimum reproducible example](https://stackoverflow.com/help/minimal-reproducible-example), e.g. a link to a self-contained [Google Colab](https://colab.research.google.com/) notebook (i.e. containing everthing needed to reproduce the bug: installation of pyannote.audio, downloads of models or test data, etc...)

* if your issue is a feature request, please [read this](https://xyproblem.info/) first and update your request accordingly.
