### ISSUE TITLE
Test option for applications

### ISSUE THREAD

**Issue by diego-fustes** [pyannote/pyannote-audio#132]
The current applications allow to train, validate and apply a model, but a testing mode is missing. This mode would apply a given model to the test dataset in the given protocol and then output the same metrics used for validation.

**Comment by hbredin** [comment]
This would be a nice addition to the library, indeed.
Here is how I would implement it, if I were to do it myself.

For `pyannote-speech-detection` and `pyannote-change-detection`, we should
-  update the "validate" mode so that it creates a `params.yml` file (similar to the one created by `pyannote-pipeline`) containing the best epoch and the corresponding best detection threshold.
- add a "test" mode that reads this `params.yml` file, extract raw scores (in the same way "apply" mode does -- but without storing them on disk), apply the best threshold, compute and report metrics,  and (optional) dump the resulting segmentation to disk (as a text file, in the same way `pyannote-pipeline` "apply" mode does)
- (optional) use `pyannote-metrics` [command line tool](http://pyannote.github.io/pyannote-metrics/cli.html) to obtain a more thorough performance report

This would look like this:
```
pyannote-speech-detection test [options] [--dump=<output_dir>] <params.yml> <database.task.protocol> 
```

For `pyannote-speaker-embedding`, we could do the same for speaker verification protocols, but I am not sure it would make much sense for speaker diarization protocols [since we assume perfect segmentation in "validate" mode](https://github.com/pyannote/pyannote-audio/blob/f880e18a12d981f673aaae23dec722406179cc2c/pyannote/audio/applications/speaker_embedding.py#L153-L159). Even for the former, it would mean that we agree that the best way of aggregating embeddings is [taking their average](https://github.com/pyannote/pyannote-audio/blob/f880e18a12d981f673aaae23dec722406179cc2c/pyannote/audio/applications/speaker_embedding.py#L359-L360) (which is probably not true).

I suggest we (you?) start with `pyannote-speech-detection` so that we can see how it goes.
What do you think?

**Comment by diego-fustes** [comment]
I can tackle the implementation of your approach, which looks reasonable. I'm starting with `pyannote-change-detection` as suggested. I'll post the link to the pull request here once done

**Comment by hbredin** [comment]
I have been [working](https://github.com/pyannote/pyannote-audio/issues/136#issuecomment-461063965) on the next release of `pyannote.audio` recently and this is the last issue I want to address before going through.

I believe we no longer need this `test` mode now that [`pyannote.pipeline`](https://github.com/pyannote/pyannote-pipeline) has been released, with its own `apply` mode that also [computes](https://github.com/pyannote/pyannote-pipeline/blob/d98f5ef042ca9dd366c46f9991be2d16ea5f72f4/pyannote/pipeline/experiment.py#L333-L335) and [displays](https://github.com/pyannote/pyannote-pipeline/blob/d98f5ef042ca9dd366c46f9991be2d16ea5f72f4/pyannote/pipeline/experiment.py#L344) the evaluation metric.

Furthermore, adding the proposed `test` mode would probably give the false impression that the returned value is the best one can achieve with the model. This is actually not true because it relies on a [sub-optimal pipeline](https://github.com/pyannote/pyannote-audio/blob/800812fabd27c939761a7c435d5ecd2250cefeb2/pyannote/audio/applications/speech_detection.py#L254-L263) where only some of the hyper-parameters are tuned. 

For instance, for speech activity detection, I'd rather have people use `validate` mode to select the *best* epoch on the development set and then [tune a fully-fledged pipeline](https://github.com/pyannote/pyannote-audio/tree/develop/tutorials/pipelines/speech_activity_detection) with `pyannote-pipeline`.  

Therefore, I am going to close this issue and the corresponding pull request.
I am very sorry that you worked on that and it ends up not being used. 
Thank you again for your contribution to the project and I hope you'll contribute again in the future!.

**Comment by diego-fustes** [comment]
Hi, that's ok, I understand that the next release has 'eaten' this feature. I've got knowledge in the process, which is the most important thing :)
