### ISSUE TITLE
ValueError: Expected argument `task` to either be `'binary'`, `'multiclass'` or `'multilabel'` but got 1

### ISSUE THREAD

**Issue by polinadumbledore** [pyannote/pyannote-audio#1364]
When I was trying to train the model, this error: 'ValueError: Expected argument `task` to either be `'binary'`, `'multiclass'` or `'multilabel'` but got 1' occured. 

this is my code:

from pyannote.database import get_protocol, FileFinder
preprocessors = {"audio": FileFinder()}
protocol = get_protocol('MyDatabase.SpeakerDiarization.MyProtocol', 
                   preprocessors=preprocessors)

from pyannote.audio.tasks import VoiceActivityDetection
vad = VoiceActivityDetection(protocol, duration=2., batch_size=128)

from pyannote.audio.models.segmentation import PyanNet
model = PyanNet(sincnet={'stride': 10}, task=vad)

import pytorch_lightning as pl
trainer = pl.Trainer(devices=1, accelerator="gpu", max_epochs=2)
trainer.fit(model)

the database looks like this:
![Снимок экрана 2023-05-08 в 19 41 15](https://user-images.githubusercontent.com/72070019/236881143-59147e0f-a727-40b3-8f07-87534cf2270f.png)

files look like this:
![Снимок экрана 2023-05-08 в 19 43 10](https://user-images.githubusercontent.com/72070019/236881666-a4888157-ba8e-40a1-991b-22f2f6308641.png)
![Снимок экрана 2023-05-08 в 19 43 29](https://user-images.githubusercontent.com/72070019/236881671-99f04383-77bd-400b-91cb-94156693c30d.png)
![Снимок экрана 2023-05-08 в 19 43 56](https://user-images.githubusercontent.com/72070019/236881672-f52df61e-aabb-49af-8ce7-b6c31b1e630b.png)

**Comment by shaunlwl** [comment]
Hi polinadumbledore, 

I faced the same issue as you, but found a quick fix.

This was primarily caused by a bug in the pyannote.audio package 2.1.1 in it's use of torchmetrics AUROC,  a hot fix for it would be to go to the package: pyannote/audio/tasks/segmentation/mixins.py. In that script, line 132 calls the AUROC metric but uses num_classes parameter as a "tasks" argument, which only accepts ['binary', 'multiclass', 'multilabel']. Instead, num_classes is passing 1 as input (due to len(self.specifications.classes)).

The Author seems to have fixed this in his develop branch, however not yet in PYPI.

Quick Fix: 

Edit you default_metric function in mixins.py as such:

from torchmetrics.classification import BinaryAUROC, MulticlassAUROC, MultilabelAUROC

    def default_metric(
        self,
    ) -> Union[Metric, Sequence[Metric], Dict[str, Metric]]:
        """Returns macro-average of the area under the ROC curve"""

        num_classes = len(self.specifications.classes)
        if self.specifications.problem == Problem.BINARY_CLASSIFICATION:
            return BinaryAUROC(compute_on_cpu=True)
        elif self.specifications.problem == Problem.MULTI_LABEL_CLASSIFICATION:
            return MultilabelAUROC(num_classes, average="macro", compute_on_cpu=True)
        elif self.specifications.problem == Problem.MONO_LABEL_CLASSIFICATION:
            return MulticlassAUROC(num_classes, average="macro", compute_on_cpu=True)
        else:
            raise RuntimeError(
                f"The {self.specifications.problem} problem type hasn't been given a default segmentation metric yet."
            )


Hope it works.
