### ISSUE TITLE
Not able to download "Speaker-Diarization" pipeline

### ISSUE THREAD

**Issue by carl-ainsworth-db** [pyannote/pyannote-audio#1402]
Hi,

I'm trying to import the "Speaker-Diarization" pipeline for Pyannote-audio but I'm seeing the error below.

![image](https://github.com/pyannote/pyannote-audio/assets/127414875/ac19d4db-bc17-4c08-b92c-c6b0df75a969)

I've accepted all required Terms and Conditions and also have an authentication code from HuggingFace that I am using.

When I try to access the link that is shown next to the error, I see a "File not Found" message in my browser.

Can you please suggest a possible workaround whilst this issue is resolved?

**Comment by danidelaparra** [comment]
Hello,

I have the exact same problem. I also created an issue (https://github.com/pyannote/pyannote-audio/issues/1399) but I haven't gotten any response. I think it's because there is no pytorch_model.bin file in the package folder (as opposed to other models that do load). Hopefully the authors upload the bin file soon or provide a workaround.

**Comment by hbredin** [comment]
@danidelaparra, your problem is a different one. I replied in #1399.

@carl-ainsworth-db seems more like a [`speechbrain`](https://github.com/speechbrain/speechbrain) problem to me. I have no idea where this `enhance_model.ckpt` checkpoint comes from. Never used it for any of the speaker diarization pipeline and I believe there has never been any in `speechbrain/spkrec-ecapa-voxceleb` Huggingface repo either.

**Comment by hbredin** [comment]
Just be aware that `pyannote/embedding` will give you much worse performance than `speechbrain/spkrec-ecapa-voxceleb` performance (like, up to twice as worse sometimes...)

**Comment by asusdisciple** [comment]
Is there any way to implement this with actual speechbrain model from spkrec-ecapa-voxceleb? I am still getting errors if i try to run it locally.
