### ISSUE TITLE
Overwritten HF cache directory prevents model preloading using HF cli

### ISSUE THREAD

**Issue by youroff** [pyannote/pyannote-audio#1484]
I'm trying to build an image where models are preloaded using `huggingface-cli download ...` however, the default cache directory is being  overwritten here:
https://github.com/pyannote/pyannote-audio/blob/develop/pyannote/audio/core/model.py#L57
https://github.com/pyannote/pyannote-audio/blob/develop/pyannote/audio/core/pipeline.py#L95

I'm using diarize model through whisperx, so I can't overwrite cache dir back to the default one at callsite, but I can probably pass this custom directory to cli. And I wonder what was the reason for such decision in the first place, and if it's even going to be stable and won't change at some point again and deoptimize my image as a result.

**Comment by Wauplin** [comment]
Hey there, I'm @Wauplin - maintainer of `huggingface_hub`. I saw this issue thanks to @youroff's ping. Please let me know if I can be of any assistance. In general it is indeed good practice to keep the same `$HF_HOME` environment variable as cache directory so that all libraries using the HF Hub shares the same cache - hence reducing the risk of file duplication. I would also be interested to know if there is a special reason to override it with a `$PYANNOTE_CACHE` variable. Maybe we can find a solution that fits your need while making sure it stays compatible with existing cache.

**Comment by hbredin** [comment]
The reason was simply to have all things related to `pyannote` in the same directory, hence `PYANNOTE_CACHE`.

Though it is very popular, Huggingface model hub is not the only hub in town and I'd rather have one cache for all things related to pyannote rather than have them separated into multiple directories depending on the model hub.

That being said, I'd be open to a PR making it easier for pyannote users to allow (but not enforce)using HF_HOME instead of PYANNOTE_CACHE if they prefer.

@youroff wouldn't setting $PYANNOTE_CACHE value to $HF_HOME solve your issue?

**Comment by youroff** [comment]
Yes, this is exactly how I ended up solving it, but it took me some time to figure out. Definitely pretty confusing for the default behavior, especially for someone new to the world of ML, such as myself.

I'm not sure I get the "one cache for all things" argument, or what benefits does it bring in particular. Unless we manage said cache in some very specific fashion to override the default behavior, I'd rather give control away to correspondent libraries. In case `pyannote` needs some special place for caching its own artifacts, I would probably provide it s a separate dir explicitly. But again, speaking from the perspective of a newbie in ML :)
