### ISSUE TITLE
Download old pre-trained models from torch.hub? 

### ISSUE THREAD

**Issue by picheny-nyu** [pyannote/pyannote-audio#1520]
I was resurrecting some old code for a student project to illustrate diarization performance. I no longer seem to be able to download the diehard models using torch.hub.load. Is this correct, and I have to upgrade to the newest pyannote version? I saw another post with the same problem (no resolution).

Thanks
Michael Picheny

**Comment by hbredin** [comment]
The old `torch.hub` is no longer supported since `pyannote 2.x` (we are now at `pyannote 3.x`).
You should revert to `pyannote 1.x` but I would not recommend that as the performance of those old models is way behind what [`pyannote/speaker-diarization-3.0`](https://huggingface.co/pyannote/speaker-diarization-3.0) can do.

**Comment by eyaler** [comment]
solution:
```
!pip install pyannote.core==4.1 pyannote.pipeline==1.5.2 pyannote.audio==1.1.1
!wget -nc https://raw.githubusercontent.com/pyannote/pyannote-audio/1.1.1/hubconf.py -P /root/.cache/torch/hub/pyannote_pyannote-audio_main
!wget -nc https://raw.githubusercontent.com/pyannote/pyannote-audio/1.1.1/hubconf.py -P /root/.cache/torch/hub/pyannote_pyannote-audio-hub_master
import torch
import pyannote.core #https://github.com/pyannote/pyannote-audio/issues/561
pipeline = torch.hub.load('pyannote/pyannote-audio', 'dia', trust_repo=True)
```
