### ISSUE TITLE
speaker-diarization-3.1 using 0% gpu

### ISSUE THREAD

**Issue by MEPO29** [pyannote/pyannote-audio#1557]
I'm using Google Colab and it is utilizing 0% gpu. Sometimes it uses 100% for a second and then it goes back to 0%. The audio is about 1.5 hours long. Is this normal behaviour? Keep in mind CPU is at 100% almost all of the time.
![image](https://github.com/pyannote/pyannote-audio/assets/83566842/8233ff06-f6a2-4c28-9ddf-5b6eb9408549)
![image](https://github.com/pyannote/pyannote-audio/assets/83566842/8d2f8b7f-7b6b-43b8-bea9-bd71062c8c98)

**Comment by MohammedAlhajji** [comment]
I somehow fixed this by using `conda install -c conda-forge pyannote.core` on my M3

**Comment by KennethTrinh** [comment]
this worked for me after uninstalling `onnxruntime` and `onnxruntime-gpu`
`pip install optimum[onnxruntime-gpu]`
See this link:
https://huggingface.co/docs/optimum/main/en/onnxruntime/usage_guides/gpu#installation

**Comment by arnavmehta7** [comment]
@KennethTrinh I don't understand how that'll work, because new version isn't dependent on onnx.

**Comment by pourmand1376** [comment]
@KennethTrinh 
I tested your solution and It didn't work for me.

**Comment by jaffee** [comment]
I found that when passing a filename to the speaker diarization pipeline, I got very poor performance. Upon profiling I discovered this was due to many many calls to `get_torchaudio_info` and `torchaudio._backend.ffmpeg._load_audio_fileobj`. This indicated to me that the file was being reprocessed many times unnecessarily (this was all coming from the "crop" method). I noticed that there were very different codepaths if the incoming file object already had a "waveform" computed, so I did the following:

```
import torchaudio

waveform, sample_rate = torchaudio.load("segment_0.wav")
audio_file = {"waveform": waveform, "sample_rate": sample_rate}
```

and then I passed audio_file to my pipeline. This took my runtime from 5m to 13s. 

I suspect it would be straightforward to change the code to perform this step internally initially and save the user the trouble... and also probably simplify a lot of the downstream code as it could just assume it always had a waveform.
