### ISSUE TITLE
How to finetune clustering and embedding models in speaker diarization pipeline? 

### ISSUE THREAD

**Issue by rkapur102** [pyannote/pyannote-audio#1578]
Hi @hbredin , how can I finetune the clustering and embedding models in the SpeakerDiarization pipeline? All tutorials only refer to finetuning the segmentation model. Any help would be appreciated.

**Comment by hbredin** [comment]
Fine-tuning speaker embedding is currently not implemented as `pyannote` relies on external libraries for that part.

You can however tune the clustering threshold to your use case. [This tutorial](https://github.com/pyannote/pyannote-audio/blob/develop/tutorials/adapting_pretrained_pipeline.ipynb) may help.

**Comment by rkapur102** [comment]
@hbredin is there a way to finetune the speaker embedding model separately and then pass it into the pyannote pipeline? I saw it is the ECAPA-TDNN model. Can that be finetuned? It seems it can be trained from scratch, but I'm looking to finetune it. Can I finetune it on my own and pass in that new finetuned embedding model to the "embedding" parameter in SpeakerDiarization()?

**Comment by hbredin** [comment]
I think this is a question for speechbrain project.

**Comment by picheny-nyu** [comment]
If I understand this correctly (and I may not) Diarization pipeline 3.0 seems to use the WeChat embeddings; older versions of the pipeline seem to use the Speechbrain version. I am a bit confused as the Plaquet paper which otherwise seems to be a good description of the pipeline still uses the Speechbrain embeddings, but maybe things changed when the pipeline became available on huggingface......

**Comment by hbredin** [comment]
Plaquet's paper comes with a companion repository (https://github.com/FrenchKrab/IS2023-powerset-diarization) that does include a pipeline based on `speechbrain` ECAPA-TDNN.
