### ISSUE TITLE
How to use SincNet for speaker change detection?

### ISSUE THREAD

**Issue by MarkChanxDjent** [pyannote/pyannote-audio#184]
Hi, I am using my own data to train a speaker change detection model with gpu. It takes nearly 1 hour to load the data and generate batches since my training data is over 1000 hours. And I found that you mentioned in [issues#143 Processing waveforms directly](https://github.com/pyannote/pyannote-audio/issues/143) that we can use SincNet to make batch generating faster.

But how can I use SincNet in speaker change detection?? How should I modify the config.yml? Thank you!

**Comment by hbredin** [comment]
> Hi, I am using my own data to train a speaker change detection model with gpu. It takes nearly 1 hour to load the data and generate batches since my training data is over 1000 hours. 

Only annotations are pre-loaded at the beginning of training.
Data loading and batch generation are then done on-the-fly.
Therefore, switching to processing waveforms directly will have no effect on this initialization time.

> And I found that you mentioned in [issues#143 Processing waveforms directly](https://github.com/pyannote/pyannote-audio/issues/143) that we can use SincNet to make batch generating faster.

Indeed, this makes online batch generation much faster -- but processing batches on the GPU is then longer because the model contains much more parameters.

> But how can I use SincNet in speaker change detection?? 
> How should I modify the config.yml? Thank you!

You should switch architecture to use `pyannote.audio.models.PyanNet` and feature extraction to use `pyannote.audio.features.RawAudio`.

I have not thoroughly tested SincNet for speaker change detection myself (though preliminary results seem promising) so I would be happy to hear some feedback from you regarding this. One could even think to write a technical report (or even submit to a conference) with results on diverse datasets.

**Comment by MarkChanxDjent** [comment]
Thanks!! I will try to do this.

**Comment by hbredin** [comment]
Closing this stalled issue. Please re-open if needed.

FYI - I tried and it works: see Table 2 in https://arxiv.org/pdf/1911.01255.pdf
