### ISSUE TITLE
How to use this package

### ISSUE THREAD

**Issue by chanansh** [pyannote/pyannote-audio#20]
Can you please supply some documentation on speaker embedding and detection? It's not clear how to use this package. Moreover does it include diarization?

**Comment by hbredin** [comment]
Sorry, this package is not ready for prime time yet.
No documentation is available for now, and it is probably going to stay like that for the next few months...

I only made it public so that people can use it to reproduce [TristouNet](http://github.com/hbredin/tristounet) paper.

Also,iIt does **not** include speaker diarization code (yet).

Please contact me directly by email or twitter DM with what you have in mind and maybe we can collaborate on this...
