### ISSUE TITLE
How to feed data into an algorithm?

### ISSUE THREAD

**Issue by haha010508** [pyannote/pyannote-audio#205]
I put my AMI data at sounddata folder and write this statement at database.yml
AMI: /mnt/***/*****/sounddata/amicorpus//audio/{uri}.wav

and run this code:
$ pyannote-change-detection apply ${TRAIN_DIR}/weights/0870.pt AMI.SpeakerDiarization.MixHeadset precomputed/scd

but the result is:
raise ValueError(msg.format(uri=uri))
ValueError: Could not find file "ES2003a.Mix-Headset".

so what is problem in my code?

**Comment by hbredin** [comment]
Can you please share the exact location and content of file `database.yml`?

```bash
$ cat /path/to/database.yml
```

and check that, if you replace `{uri}` by `ES2003a.Mix-Headset`, the corresponding wav file actually exists?

**Comment by chrisspen** [comment]
I'm having a similar problem. Is there any documentation for how to install the AMI database?

The problem here seems to be that "/mnt//**/sounddata/amicorpus//audio/{uri}.wav" is not a valid path or even template path, since there are double slashes and glob notation that pyannotate doesn't support. That said, even if I specify an absolute path, but still containing the {uri} variable, I still get a similar error.

**Comment by chrisspen** [comment]
Try fixing the repeated slash with something like:

    AMI: /mnt//**/sounddata/amicorpus/*/audio/{uri}.wav

**Comment by hbredin** [comment]
Closing this stalled issue. Please re-open if needed.
