### ISSUE TITLE
fix: cropping audio files outside file range

### ISSUE THREAD

**Issue by PaulLerner** [pyannote/pyannote-audio#332]
Hi,
When training embeddings with an erroneous UEM (which says that the file is annotated outside of the file range), we get a warning from https://github.com/pyannote/pyannote-audio/blob/develop/pyannote/audio/features/utils.py#L336 because SoundFile failed to seek but that's it.
We don't get any error from RawAudio nor SlidingWindowFeature, so I'm not sure where you want to handle this

cc: @juanmc2005

**Comment by hbredin** [comment]
The first obvious solution would be to fix the UEM.

Now, let's talk about what is actually happening...
When `SlidingWindowFeature` is asked to `crop` outside of its extent with a `fixed` duration, it will simply repeat the first (if asked to crop before the start time) or the last (if asked to crop after the end time) samples until there is enough samples to match the requested `fixed` duration:
https://github.com/pyannote/pyannote-core/blob/bc1506515c4245bdf898aec29dd3e84f1dd56181/pyannote/core/feature.py#L203-L212

I don't (yet) understand why this is happening because the following lines do crop the UEM to fit in the actual file range: 
https://github.com/pyannote/pyannote-audio/blob/b98a797c8f1a8722de2e8fc65943ffe56d3d7b64/pyannote/audio/labeling/tasks/base.py#L267-L270

But the above only applies for labeling tasks (e.g. speech activity detection or speaker change detection) and is not implemented for embeddings.

I guess the problem only occurs for embeddings? Can you confirm? 

A fix could be to update this line and crop the `annotation` in the same way as it is done for labeling tasks:

https://github.com/pyannote/pyannote-audio/blob/b98a797c8f1a8722de2e8fc65943ffe56d3d7b64/pyannote/audio/embedding/generators.py#L136-L137

**Comment by PaulLerner** [comment]
> I guess the problem only occurs for embeddings? Can you confirm?

It doesn't happen for SCD

Should I fix it (the way you suggested it) ?

**Comment by hbredin** [comment]
Yes, please!

**Comment by hbredin** [comment]
Thanks!
