### ISSUE TITLE
Best way to Label Segments for SAD

### ISSUE THREAD

**Issue by picheny-nyu** [pyannote/pyannote-audio#357]
I have a question about the best way to label for SAD. You can see from the attached picture that I have a sequence of segments that are "close" together. I label each one as a separate segment for SAD. However, the SAD detector groups them all together. Does this cause more errors during scoring? Should I label a sequence of segments that are effectively next to each other as a single segment of speech? If so, what is the minimum gap between segments to use to label a sequence as two speech segments rather than one. 

<img width="1018" alt="Screen Shot 2020-04-16 at 2 32 46 PM" src="https://user-images.githubusercontent.com/55798528/79493390-6b294700-7fef-11ea-8ce8-e90806f58d68.png">

**Comment by hbredin** [comment]
The model will try to mimic your annotations so it really depends on your final application.

For instance, comparing `sad_dihard` and `sad_ami` pretrained models, you'll notice that `sad_dihard` will allow for short non-speech regions while `sad_ami` will tend to merge them. This is mostly due to the way `dihard` and `ami` were annotated in the first place.

As far as scoring is concerned, you may want to add [a forgiveness `collar`](http://pyannote.github.io/pyannote-metrics/reference.html?highlight=collar) at evaluation time to not evaluate regions around speech turn boundaries.

**Comment by hbredin** [comment]
Closing stalled issue. Please re-open if needed.
