### ISSUE TITLE
Custom dataset for speaker embedding

### ISSUE THREAD

**Issue by vbrignatz** [pyannote/pyannote-audio#387]
Hello

I am trying to use a custom made dataset to train a x-vector extractor.
When using a custom dataset configured in ```database.yml```, it seems your program only accept ```SpeakerDiarization``` tasks, as seen in the file pyanotte-database/pyannote/database/custom.py.
```
# only speaker diarization TASKS are supported for now...
if task_name != 'SpeakerDiarization':
    msg = (
        'Only speaker diarization protocols are supported for now.'
        )
    raise ValueError(msg)
```

I was wondering if you plan on adding support for ```SpeakerVerification``` tasks. 
If you plan on adding the feature but haven't worked on it, I could try to do it.

**Comment by hbredin** [comment]
Hi @vbrignatz, 

Thanks for your interest in `pyannote.audio` and willing to contribute. 
That's very much appreciated!

You are right that `pyannote.database` only supports custom speaker diarization protocols for now. 

However, if your goal is only to train x-vectors, you most likely do not need to define a `SpeakerVerificationProtocol`: a `SpeakerDiarizationProtocol` should work just fine, even if there is only one speaker per file. 

If you look closer, you will notice that [`SpeakerVerificationProtocol`](https://github.com/pyannote/pyannote-database/blob/6b0d78962358c1efd45d664392d2f672a3c166e5/pyannote/database/protocol/speaker_verification.py#L34) is nothing but a `SpeakerDiarizationProtocol` with [additional `trial` methods](https://github.com/pyannote/pyannote-database/blob/6b0d78962358c1efd45d664392d2f672a3c166e5/pyannote/database/protocol/speaker_verification.py#L121-L140). 

Those `trial` methods are not used for training the model. Only regular `SpeakerDiarizationProtocol` [`subset`](https://github.com/pyannote/pyannote-database/blob/6b0d78962358c1efd45d664392d2f672a3c166e5/pyannote/database/protocol/speaker_diarization.py#L59) methods are [used](https://github.com/pyannote/pyannote-audio/blob/06f76a2c5a37c79cf42710167c7b7404658879d3/pyannote/audio/embedding/generators.py#L133) for training embeddings.

That being said, if you also want to run validation experiments in the same way it is done for VoxCeleb [in the tutorial](https://github.com/pyannote/pyannote-audio/tree/develop/tutorials/models/speaker_embedding#validation), then, yes, we would need to update the `pyannote.database.custom` codebase.

cc @PaulLerner because we already discussed refactoring the `pyannote.database.custom` database to support additional scenarii and he might be interested in this discussion.

**Comment by vbrignatz** [comment]
Thanks for the response

I'll try to train a x-vector system with a ```SpeakerVerificationProtocol```.
In the meantime, I'll keep studying your code to find the changes to implement to allow custom verification protocols.

For most common verification dataset (I'm thinking about [SITW](http://www.speech.sri.com/projects/sitw/)), is it possible to use pyanotte-db-template to facilitate their usage ?

**Comment by hbredin** [comment]
`pyannote-db-template` is not really up to date, sorry about that.

I recommend you have a look at [`pyannote.db.voxceleb`](https://github.com/pyannote/pyannote-db-voxceleb) instead.

**Comment by vbrignatz** [comment]
hi @hbredin, can you link the https://github.com/pyannote/pyannote-database/pull/55 to this issue and close it ?
