### ISSUE TITLE
python first

### ISSUE THREAD

**Issue by danFromTelAviv** [pyannote/pyannote-audio#425]
Thanks for creating this great library!

The reason that I want to use this library over kaldi is that it is python native and still close to SOTA. 

However, after trying to use and learn this library I see that it is very "bash first". 

I really think you should consider making this library python first - meaning that everything is done with code rather than command-line commands. This will allow others to much more easily debug issues and adjust the code to their needs. In turn, this will become an even more popular library since it will have a significant differentiation from other audio pipelines.  

On a more practical note:
I would like to see an end to end tutorial for training on my own data and using the trained models for speaker diarization through python code. I imagine that this is the generic use case that this library was intended for in the first place...

Thanks!
Dan

**Comment by hbredin** [comment]
(One of) the reason why I built this library is mostly because I was scared of diving into Kaldi code :-)

The main reason why it is _bash first_ is that I wanted to force users (including myself) to follow best machine learning practices: see this introductory [video](https://youtu.be/37R_R82lfwA?t=294) for context.

That being said, I am currently in the process of [converting](https://github.com/pyannote/pyannote-audio/pull/407) the whole code base to pytorch-lightning.  
Would you be willing to help on the PR? 

Once this is done (no ETA unfortunately), it will be usable as a _Python first_ library.

**Comment by danFromTelAviv** [comment]
I would gladly put in an hour or two per week to help out this project. Let me know what needs to be done.

As for the bash first. Reproducibility is key. To do that you need to keep a record of your experiments. config files are fine for that. 
That's not my core concern though. What I mean is:
>> apply(parrams) instead of $ pyannote-audio apply params. It effectively does the same thing. It really helps with debugging though because you have access to breakpoints...

**Comment by hbredin** [comment]
> I would gladly put in an hour or two per week to help out this project. 

That would be great! Thanks.

> Let me know what needs to be done.

A lot! 

The first thing would probably be to try using the current version of the `pytorch-lightning` PR.
https://github.com/pyannote/pyannote-audio/tree/pytorch-lightning
However, tutorials have yet to be updated to match the new `pyannote-audio` command line interface -- so this would probably be tricky.

Also, since I don't really know your background, I guess I'll create new issues with the `help wanted` tag and you can always decide to jump in when you think you can help. What do you think?


> As for the bash first. Reproducibility is key. To do that you need to keep a record of your experiments. config files are fine for that.
> That's not my core concern though. What I mean is:
> `>> pyannote.audio.apply(parrams)` instead of `$ pyannote-audio apply params`. It effectively does the same thing. It really helps with debugging though because you have access to breakpoints...
> 
> I saw that inside your code this also exists already. But it's not the primary method and it's not as clean since it wasn't meant to be ran like that.

Yes, you are right. It exists but it not as clean nor is documented. I plan to work on the documentation part when I am done with the `pytorch-lightning` PR.

**Comment by danFromTelAviv** [comment]
Ok - that works. Please tag me as well if you can in the issues so I get a reminder in my email. 

For reference - my background is around efficient neural nets in computer vision - but I've been working on speech recognition for a couple of years now. So Algorithms, neural networks - more on the research side than dev side but everything I work on is aimed at production so hopefully I picked up a couple of best practices along the way :)

**Comment by mogwai** [comment]
Think version two is moving towards this now. Can we close this issue on the release of version 2?

**Comment by hbredin** [comment]
Yes, version 2 will address this issue.

One can already try the Python-first API described in `develop` branch [README](https://github.com/pyannote/pyannote-audio/tree/develop#neural-speaker-diarization-with-pyannoteaudio).
