### ISSUE TITLE
Pre-trained model

### ISSUE THREAD

**Issue by ChristopherLu** [pyannote/pyannote-audio#49]
Is there a trained `TristouNet` on ETAPE that I can use for domain adaption on my task of speaker turn detection?

**Comment by hbredin** [comment]
Yes. See https://github.com/pyannote/pyannote-audio/tree/master/tutorials/speaker-embedding#pretrained-model

Since ETAPE is French news broadcast dataset, I suspect the model will not work that well in another language. I'd be happy to hear your feedback on how successful you were at adapting to your own data.

That being said, I suggest you use the `--start` option of `pyannote-speaker-embedding train` to do domain adaptation. See `pyannote-speaker-embedding --help` for a description of available options.
