### ISSUE TITLE
SoundFile failed to seek-and-read ...

### ISSUE THREAD

**Issue by Gabrielk99** [pyannote/pyannote-audio#689]
Hello, i'm trying train the model SpeakerActivationDetection, with "pyannote-audio sad train .... my_data_set ", and i receive this mensage : 

/home/gabriel/.local/lib/python3.8/site-packages/pyannote/audio/features/utils.py:351: UserWarning: SoundFile failed to seek-and-read in /home/gabriel/Desktop/My_tasks/IA-DEEPLEARNING/IC/Codigos/data_vale/audio/ACV1991.wav: loading the whole file...

i executed before a simple tutorial that just aply the pipeline directly in my own data, and work, no problem.

**Comment by hbredin** [comment]
As the warning (not an error) message states, it means that SoundFile cannot "seek" into the file (i.e. jump to random position). Jumping to random positions in a file is needed to make training faster. Right now, your training  will be slower because of this particular file. 

You did not get this warning when applying a pretrained model because there is no need to "seek" into the file at inference time: one only has to read the whole file in order.

Why this happens is another question, your file is most likely (at least partially) corrupted.
Try opening it with `scipy.io.wavfile.read` and save it again to disk, this usually solves the problem.

**Comment by Gabrielk99** [comment]
oh fast, thank you, well, i see its a warning but the process exit without training. 

I had never come across this kind of situation, thank you.

i will try again later, thank you very mutch.

**Comment by Gabrielk99** [comment]
i have a one way for disable the warnings?
