### ISSUE TITLE
ModuleNotFoundError: No module named 'pyannote.audio.pipelines'

### ISSUE THREAD

**Issue by xinyi1214** [pyannote/pyannote-audio#691]

**Comment by yilmazay74** [comment]
I am having exactly the same issue. isn' there any solution for this issue yet?

**Comment by yilmazay74** [comment]
Actually pyannote.audio is installed successfully through pip install. Furthermore pipelines is under pyannote.audio.  Why can't it see pipelines module under pyannote.audio ?  It looks like it is a python path issue, but I could not figure out how to overcome it. Any comments or suggestions will be appreciated.

**Comment by yilmazay74** [comment]
Anyways, I found myself a workaround solution:
instead of saying:
from pyannote.audio.pipelines import SpeakerDiarization

I changed it as below:
import sys
sys.path.append("/home/ubuntu/Projects/pyannote-audio/pyannote/audio/pipelines")
import speaker_diarization

However, this time it gave another error, related with circular import :

ImportError: cannot import name '__version__' from partially initialized module 'pyannote.audio' (most likely due to a circular import) (/home/ubuntu/Projects/pyannote-audio/pyannote/audio/__init__.py)

**Comment by aoussou** [comment]
@yilmazay74 

Are you using PyCharm by any chance? I get the same circular import error in the IDE but if works fine in the command line.
