### ISSUE TITLE
Use pyannote-audio 2.0 to train with config.yaml in Huggingface

### ISSUE THREAD

**Issue by shipnight** [pyannote/pyannote-audio#829]
I've written my database.yml, as the tutorial says.
I want to use the [Configuration file](https://huggingface.co/pyannote/segmentation/blob/main/config.yaml) to train a new segmentation model with my own database. But the tutorial doesn't mention how to use this to train.
I want to know what I should do.

**Comment by hbredin** [comment]
There is no easy way to re-use the `config.yml` file, for now.
I'd happily merge a PR that updates [this training script](https://github.com/pyannote/pyannote-audio/blob/develop/pyannote/audio/cli/train.py) to take an existing `config.yml` as input.

In the meantime, you can follow [this tutorial](https://github.com/pyannote/pyannote-audio/blob/develop/tutorials/fine_tuning.ipynb) with the following modifications:
* use `Segmentation` task instead of `VoiceActivityDetection`
* instantiate `Segmentation` task with [these](https://huggingface.co/pyannote/segmentation/blob/main/config.yaml#L3-L17) parameters from `config.yml`
* instantiate `PyanNet` model with [these](https://huggingface.co/pyannote/segmentation/blob/main/config.yaml#L18-L27) parameters from `config.yml`

**Comment by shipnight** [comment]
> There is no easy way to re-use the `config.yml` file, for now. I'd happily merge a PR that updates [this training script](https://github.com/pyannote/pyannote-audio/blob/develop/pyannote/audio/cli/train.py) to take an existing `config.yml` as input.
> 
> In the meantime, you can follow [this tutorial](https://github.com/pyannote/pyannote-audio/blob/develop/tutorials/fine_tuning.ipynb) with the following modifications:
> 
> * use `Segmentation` task instead of `VoiceActivityDetection`
> * instantiate `Segmentation` task with [these](https://huggingface.co/pyannote/segmentation/blob/main/config.yaml#L3-L17) parameters from `config.yml`
> * instantiate `PyanNet` model with [these](https://huggingface.co/pyannote/segmentation/blob/main/config.yaml#L18-L27) parameters from `config.yml`

Thanks for your reply!I have followed your advice and successfully trained the segmentation model. 
But when I use **the same database.yaml** to train the embedding model, I get the following error:
_ raise MisconfigurationException(
pytorch_lightning.utilities.exceptions.MisconfigurationException: Total length of `Dataloader` across ranks is zero. Please make sure that it returns at least 1 batch._

All my parameters are derived from [this](https://huggingface.co/pyannote/embedding/blob/main/config.yaml) , but I omitted some. 
The specific code is as follows：
`from pyannote.database import get_protocol
ami = get_protocol('AMI.SpeakerDiarization.MixHeadset')

arconfig={........}
from pyannote.audio.tasks import SupervisedRepresentationLearningWithArcFace
arc= SupervisedRepresentationLearningWithArcFace(ami,**arconfig) 

from pyannote.audio.models.embedding import XVectorSincNet
from_scratch = XVectorSincNet(task=arc)

import pytorch_lightning as pl
trainer = pl.Trainer(gpus=1,max_epochs=100)
trainer.fit(from_scratch)
`

**Comment by hbredin** [comment]
It could be because your training dataset only contains a (too) small number of speakers.

That being said, I wouldn't recommend using pyannote for training speaker embedding
As of January 2022, speechbrain's speaker embedding are much better than pyannote's.
