### ISSUE TITLE
Ctrl ne fonctionne pas

### ISSUE THREAD

**Issue by J-Petiot** [pyannote/pyannote-audio#969]
[SHIFT + left] et [SHIFT + right] fonctionnent (déplacement du temps de début)
[CTRL + left] et [CTRL + right] ne fonctionnent pas.
https://github.com/pyannote/pyannote-audio/pull/950#issuecomment-1123733153

**Comment by J-Petiot** [comment]
Maybe we can change CTRL and SHIFT for other keys if they are some problems on mac.

**Comment by hbredin** [comment]
I am afraid that we will have to go this way, indeed.
Maybe instead of CTRL+`key`, we could go with `key` directly.
The one problem I see is finding two pairs of keys that are next to each other for any keyboard layout...  

Example: Q S for start time and L M for end time will work for AZERTY layout but not for QWERTY.

**Comment by J-Petiot** [comment]
Maybe we can add an argument to the recipe like "keyboard" to AZERTY or QWERTY ?

**Comment by hbredin** [comment]
Better: find a Python library that does this automatically :)

**Comment by hbredin** [comment]
Any update on this? 

It is really difficult to modify the start/end time without keyboard shortcuts, using only the mouse.

**Comment by J-Petiot** [comment]
Well that's a good news for the shortcuts haha
I've looked into it, it doesn't seem so trivial, the solutions won't work 100% on all keyboard layouts, the best is the parameter I think
